[book]
authors = ["安竹 洋平"]
language = "ja"
multilingual = false
src = "src"
title = "令和3年 小平市議会 まとめ"
description = "令和3年（1月～12月）の小平市議会で起きていることを、情報公開と自身の勉強を兼ねてまとめています。議案の内容、主な質疑、一般質問、私（安竹）のコメント等です。"

[output.html]
theme = "theme"
git-repository-url="https://github.com/yasutakeyohei/reiwa3"
google-analytics="UA-144705402-1"
additional-css=["custom.css"]
additional-js=["src/js/sortable.advanced.js", "src/js/medium-zoom.js"]

[output.html.fold]
enable = true
level = 0

[output.html.search]
enable = false

[output.html.print]
enable = false

[output.z]
command = "python ../../postprocess.py"
optional = true
